services:
  web:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./src/:/app/src
    environment:
      GRANIAN_LOG_LEVEL: "debug"
      GRANIAN_PORT: "8000"
      GRANIAN_RELOAD: "1"
      GRANIAN_WORKERS: "4"
      RUST_BACKTRACE: "full"
