# fly.toml app configuration file generated for hub-api-lingering-cloud-1539 on 2025-05-07T14:56:45-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hub-api-lingering-cloud-1539'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
